function createfigure(X1, YMatrix1, XMatrix1, YMatrix2, EMatrix1)
%CREATEFIGURE(X1, YMATRIX1, XMATRIX1, YMATRIX2, EMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  XMATRIX1:  errorbar x matrix
%  YMATRIX2:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix

%  Auto-generated by MATLAB on 06-May-2016 23:43:44

% Create figure
figure1 = figure('PaperOrientation','landscape','PaperSize',[11 8.5],...
    'Color',[1 1 1]);

% Create axes
axes('Parent',figure1,'Tag','suplabel','Position',[0.09 0.07 0.855 0.895]);
axis off

% Create title
% title('Size Distribution of Trial at Trial1','VerticalAlignment','middle');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2.5);
set(plot1(1),'DisplayName','NaCl = 0   mM','Color',[1 0 1]);
set(plot1(2),'DisplayName','NaCl = 0.1 mM','Color',[1 0 0]);
set(plot1(3),'DisplayName','NaCl = 1.0 mM', 'Color',[0 1 0]);
set(plot1(4),'DisplayName','NaCl = 10  mM', 'Color',[0 0 1]);

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(XMatrix1,YMatrix2,EMatrix1,'LineWidth',1);
set(errorbar1(1),'Color',[1 0 1]);
set(errorbar1(2),'Color',[1 0 0]);
set(errorbar1(3),'Color',[0 1 0]);
set(errorbar1(4),'Color',[0 0 1]);

% Create xlabel
xlabel('Equivalent Diameter /\mum');

% Create ylabel
ylabel('Count #');

%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 10]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 150]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14,'LineWidth',1.75,'TitleFontSizeMultiplier',1,...
    'TitleFontWeight','normal','XGrid','off');
% Create legend
legend(axes1,'NaCl = 0    mM', 'NaCl = 0.1 mM', 'NaCl = 1    mM', ...
    'NaCl = 10  mM');

