function createfigure4ppt(X1, YMatrix1)
    %CREATEFIGURE(X1, YMATRIX1)
    %  X1:  vector of x data
    %  YMATRIX1:  matrix of y data
    
    %  Auto-generated by MATLAB on 15-Mar-2016 14:34:07
    
    % Create figure
    figure1 = figure;
    
    % Create axes
    axes1 = axes('Parent',figure1);
    hold(axes1,'on');
    
    % Create multiple lines using matrix input to plot
    plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineStyle','--');
    set(plot1(1),'DisplayName','FITC','LineWidth',2,'Color',[0 1 0],...
        'LineStyle','-');
    set(plot1(2),'DisplayName','FITC-std','Color',[0 1 0]);
    set(plot1(3),'Color',[0 1 0]);
    set(plot1(4),'DisplayName','TRITC','LineWidth',2,'Color',[1 0 0],...
        'LineStyle','-');
    set(plot1(5),'DisplayName','TRITC-std','Color',[1 0 0]);
    set(plot1(6),'Color',[1 0 0]);
    
    % Create xlabel
    xlabel('\Delta t [s]');
    
    % Create ylabel
    ylabel('Intensity');
    
    % Create title
    title('360 \mum Intensity Distribution');
    
    %% Uncomment the following line to preserve the Y-limits of the axes
    % ylim(axes1,[-5000 40000]);
    grid(axes1,'on');
    % Set the remaining axes properties
    set(axes1,'FontSize',15);
    % Create legend
    legend(axes1,'show');
    
