function tifData = getTifData(filename)
% 
    [~, name, ext] = fileparts(filename);
    imageInfo=imfinfo(filename);
    imageWidth=imageInfo(1).Width;
    imageHeight=imageInfo(1).Height;
    
    vBin=96/imageInfo(1).YResolution;
    hBin=96/imageInfo(1).XResolution;
    
    numFrames=length(imageInfo);
    imageData=zeros(imageHeight,imageWidth,numFrames,'uint16');
    %         exposureTime = imageInfo(1).UnknownTags(13).Value;
    %         cycleTime = imageInfo(1).UnknownTags(15).Value;
    %         frameRate = 1.0/cycleTime;
    %         sensorTemp = imageInfo(1).UnknownTags(6).Value;
    
    
    
    warning('off','MATLAB:imagesci:Tiff:libraryWarning');
    warning('off','MATLAB:imagesci:tiffmexutils:libtiffWarning');
    imageData = imread(filename);
    
    varname = genvarname(name);
    
    tifData =  struct(...
        'numFrames',{numFrames}',...
        'imageData',{imageData},...
        'verticalBinning',{vBin},...
        'horizontalBinning',{hBin});
    
    %     tifData =  struct(...
    %         'numFrames',{numFrames}',...
    %             'exposureTime',{exposureTime},...
    %             'cycleTime',{cycleTime},...
    %             'frameRate',{frameRate},...
    %             'sensorTemp',{sensorTemp},...
    %     'imageData',{imageData},...
    %         'cameraDelay',{cameraDelay},...
    %         'verticalBinning',{vBin},...
    %         'horizontalBinning',{hBin});
end